version: '3.4'

services:
  test:
    image: test:dev
    build:
      target: base
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_test$
    volumes:
      - D:\sources\repos\test-net-core\Test:/app
      - C:\Users\jarob\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_test$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_test$ bin/Debug/netcoreapp2.1/Test.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
